# SPDX-FileCopyrightText: 2026 e-Cidade community
# SPDX-License-Identifier: AGPL-3.0-or-later
version: 2
updates:
  - package-ecosystem: composer
    directories:
      - /
      - /vendor-bin/*
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 10
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:15"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 10
    labels:
      - dependencies

  - package-ecosystem: docker
    directory: /.docker/php
    ignore:
      - dependency-name: node
        update-types:
          - version-update:semver-major
    schedule:
      interval: weekly
      day: monday
      time: "09:18"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 5
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:20"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 10
    labels:
      - dependencies
