# SPDX-FileCopyrightText: 2026 e-Cidade community
# SPDX-License-Identifier: AGPL-3.0-or-later
blank_issues_enabled: true
contact_links:
  - name: Discussões da comunidade e-Cidade
    url: https://github.com/e-cidade/e-cidade/discussions
    about: Use este espaço para assuntos sobre o ecossistema e-Cidade que não sejam específicos deste site.
